name: RenewPHX
favicon: null
layout_spectrum: 0.24614
typography_spectrum: 0.18763
title: Better Together
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.9375
  lightness: 0.4888679573778063
  saturation: 0.40555361937731504
  rhythmicContrast: 0.1666567085776478
purpose: []
